name: Update matches

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Generate matches
      run: |
        curl -s "https://v3.football.api-sports.io/fixtures?date=$(date +%Y-%m-%d)" \
        -H "x-apisports-key: ${{ secrets.API_KEY }}" > raw.json

        node parse.js

    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add matches.json
        git commit -m "update matches" || echo "no changes"
        git push
